event_inherited();
var toppin = "sausage";
spr_intro = scr_get_toppin_sprite(toppin, "intro");
spr_idle = scr_get_toppin_sprite(toppin, "idle");
spr_run = scr_get_toppin_sprite(toppin, "run");
spr_panic = scr_get_toppin_sprite(toppin, "panic");
spr_taunt = scr_get_toppin_sprite(toppin, "taunt");
spr_intro_strongcold = spr_xmassausagetoppin_intro;
spr_idle_strongcold = spr_xmassausagetoppin_idle;
spr_run_strongcold = spr_xmassausagetoppin_walk;
