scr_initenemy();
killbyenemy = false;
pizzahead = true;
elite = true;
elitehit = 4;
prevhp = elitehit;
destroyable = true;
fakepepspawn = 200;
clonespawn = 150;
junkspawn = 100;
junkID = -4;
shakestun = false;
invincible = true;
grav = 0.5;
hsp = 0;
vsp = 0;
state = states.walk;
stunned = 0;
alarm[0] = 150;
roaming = true;
collectdrop = 5;
flying = false;
straightthrow = false;
cigar = false;
cigarcreate = false;
stomped = false;
shot = false;
reset = false;
flash = false;
landspr = obj_player1.character == "E" ? spr_ditto_idle : spr_fakepeppino_idle;
idlespr = obj_player1.character == "E" ? spr_ditto_idle : spr_fakepeppino_idle;
fallspr = obj_player1.character == "E" ? spr_ditto_fall : spr_fakepeppino_fall;
stunfallspr = obj_player1.character == "E" ? spr_ditto_stun : spr_fakepeppino_stun;
walkspr = obj_player1.character == "E" ? spr_ditto_idle : spr_fakepeppino_idle;
turnspr = obj_player1.character == "E" ? spr_ditto_idle : spr_fakepeppino_idle;
recoveryspr = obj_player1.character == "E" ? spr_ditto_idle : spr_fakepeppino_idle;
grabbedspr = obj_player1.character == "E" ? spr_ditto_stun : spr_fakepeppino_stun;
scaredspr = obj_player1.character == "E" ? spr_ditto_idle : spr_fakepeppino_idle;
ragespr = obj_player1.character == "E" ? spr_ditto_idle : spr_fakepeppino_idle;
spr_dead = obj_player1.character == "E" ? spr_ditto_stun : spr_fakepeppino_stun;
image_xscale = -1;
hp = 1;
slapped = false;
grounded = true;
birdcreated = false;
boundbox = false;
important = false;
heavy = false;
depth = 0;
paletteselect = 0;
spr_palette = palette_cheeseslime;
sprite_index = spr_slimemove;
grabbedby = 0;
stuntouchbuffer = 0;
scaredbuffer = 0;
snotty = false;
